app/views/main.py
from flask import Blueprint,render_template,request,flash,get_flashed_messages,redirect,current_app,url_for
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from app.models import Posts
from app.forms import PostForm
from flask_login import current_user
from app.exts import db



main = Blueprint('main',__name__)
@main.route('/',methods=['GET','POST'])
def shouye():
    return render_template('user/shouye.html')

@main.route('/index/',methods=['GET','POST'])
def index():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:#如果登录
            #获取当前用户
            u = current_user._get_current_object()
            p = Posts(title=form.title.data,content=form.content.data,user=u)
            db.session.add(p)
            return redirect(url_for('main.index'))
        else:
            flash("请先登录")
            return redirect(url_for('users.login'))
    #调取所有发表的博客
    # posts = Posts.query.filter_by(rid=0).all()
    #www.baidu.com?page=1
    #接收用户 url传递过来的 page参数
    page = request.args.get('page',1,type=int)
    pagination = Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()).paginate(page,per_page=5,error_out=False)
    posts = pagination.items
    return render_template('main/index.html',form=form,posts=posts,pagination=pagination)

# @main.route('/token/',methods=['GET','POST'])
# def token():
#     s = Serializer(current_app.config['SECRET_KEY'],expires_in=3600)
#     return s.dumps({'id':666})
#
# @main.route('/check/',methods=['GET','POST'])
# def check():
#     t = 'eyJhbGciOiJIUzUxMiIsImlhdCI6MTU0NzUzNzQ2OCwiZXhwIjoxNTQ3NTQxMDY4fQ.eyJpZCI6NjY2fQ.oVWgGFIS9ew0pZrzqk-5RetoUSBuPeimbMN4E7R1hveFhC3BAQlOSy-IH-0lBH7GnkaDvf2fasAMKmFCci4HiA'
#     s = Serializer(current_app.config['SECRET_KEY'])
#     data = s.loads(t)
#     return str(data['id'])

app/views/posts.py
from flask import Flask,Blueprint,jsonify
from app.exts import db
from flask_login import current_user

posts = Blueprint("posts",__name__)

@posts.route('/collect/<int:pid>')
def collect(pid):
    #判断是否收藏
    if current_user.is_favorite(pid):
        current_user.del_favorite(pid)
    else:
        current_user.add_favorite(pid)
    return jsonify({'result':'ok'})

app/templates/main/index.html
{% extends 'common/base.html' %}
{% from 'common/macro.html' import pagination_show%}
{% block title %}

    首页
{% endblock %}

{% block page_content %}
    {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}</strong>
            </div>
    {% endfor %}
    {{ wtf.quick_form(form) }}
    {% for post in posts %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static',filename='upload/'+post.user.icon) }}" alt="用户头像">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right">{{ moment(post.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ post.title }}</h4>
                {{ post.content }}
                ...
            </div>
                {% if current_user.is_authenticated %}
                    <div url="{{ url_for('posts.collect',pid=post.id) }}" class="collect" style="cursor: pointer">
                        {% if current_user.is_favorite(post.id) %}
                            取消收藏
                        {% else %}
                            收藏
                        {% endif %}
                    </div>
                {% endif %}
        </div>
    {% endfor %}
    {{ pagination.links }}
    {# {{ pagination_show(pagination,'main.index') }} #}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        $(function () {
            $('.collect').click(function () {
                _this = this
                $.get($(this).attr('url'),function () {
                    if($(_this).text() == '收藏'){
                        $(_this).text('取消收藏')
                    }else{
                        $(_this).text('收藏')

                    }
                });
            });
        });
    </script>
{% endblock %}