app/models/users.py
from app.exts import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask import current_app,flash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin
from app.exts import login_manager
from .posts import Posts
#UserMixin 查看该用户是否登录 以及 是否是匿名用户

class User(UserMixin,db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer,primary_key=True,autoincrement=True,nullable=False)
    username = db.Column(db.String(50),nullable=False,unique=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(128),nullable=False)
    confirmed = db.Column(db.Boolean,default=False)
    icon = db.Column(db.String(64),default='default.jpg')
    #lazy 在这里是懒加载 dynamic表示不加载数据但是提供查询
    #如果一对一的关系 需要加上 uselist=Flase
    posts = db.relationship("Posts",backref="user",lazy="dynamic")
    favorites = db.relationship('Posts', secondary='collections', backref=db.backref('useres', lazy='dynamic'),lazy='dynamic')

    # 添加收藏功能
    # 判断用户是否收藏了
    def is_favorite(self, pid):
        # 先获取所有收藏的博客
        favorites = self.favorites.all()
        post = list(filter(lambda p: p.id == pid, favorites))
        if len(post) > 0:
            return True
        return False

    # 添加收藏功能
    def add_favorite(self, pid):
        p = Posts.query.get(pid)  # 先根据id 查询出来
        self.favorites.append(p)  # 然后追加到 第三张表中

    # 取消收藏功能
    def del_favorite(self, pid):
        p = Posts.query.get(pid)  # 先根据id 查询出来
        self.favorites.remove(p)  # 从第三张表中 移除
    #当前用户通过 user 访问 posts 表中的字段
    #密码不能读 而且永不返回
    @property
    def password(self):
        raise AttributeError("密码不可读的帅哥")

    #设置密码的时候  保存的是加密后的hash值
    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    #校验密码是否正确 正确 true 错误 false
    #先加密 再跟数据库比较
    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    #生成token   通过邮箱发送给用户
    def generate_active_token(self,expires_in=3600):
        s = Serializer(current_app.config['SECRET_KEY'],expires_in=expires_in)
        return s.dumps({'id':self.id})

    # 验证token 方法
    @staticmethod
    def check_active_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        #这个id是从 token中解析出来的  然后根据id 到数据库中查找  对应的数据进行更新
        u = User.query.get(data.get('id'))
        if not u:
            flash("该用户不存在")
            return False
        if not u.confirmed:
            u.confirmed = True
            db.session.add(u)
        return True

#登录成功以后 执行以下方法 回调函数 获取登录用户的相关信息
@login_manager.user_loader
def load_user(uid):
    return User.query.get(int(uid))

app/forms/users.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField
from wtforms.validators import DataRequired,Length,EqualTo,Email
from wtforms.validators import ValidationError
from flask_wtf.file import FileField,FileRequired,FileAllowed
from app.models import User #自定义验证函数 用户提交检测数据中是否存在
from app.exts import photos #只能上传图片
#用户注册表单
class RegisterForm(FlaskForm):
    username = StringField('用户名',validators=[DataRequired(),Length(6,20,message="用户名必须在6到20位之间")])
    email = StringField('Email',validators=[Email(message="邮箱格式不正确")])
    password =PasswordField('密码',validators=[DataRequired(),Length(6,20,message="密码长度必须在6到20位之间")])
    confirm = PasswordField('确认密码',validators=[EqualTo('password',message="两次密码不一致")])
    submit = SubmitField('立即注册')

    def validate_username(self,filed):
        if User.query.filter_by(username=filed.data).first():
            raise ValidationError("该用户已经注册请选择其它用户")

    def validate_email(self, filed):
        if User.query.filter_by(email=filed.data).first():
            raise ValidationError("该邮箱已经被占用请用其它邮箱")


#用户登录表单
class LoginForm(FlaskForm):
    username = StringField('用户名',validators=[DataRequired(),Length(6,20,message="用户名必须在6到20位之间")])
    password =PasswordField('密码',validators=[DataRequired(),Length(6,20,message="密码长度必须在6到20位之间")])
    remember = BooleanField('记住我')
    submit = SubmitField('立即登录')
#用户上传表单
class UploadForm(FlaskForm):
    icon = FileField("头像",validators=[FileRequired(),FileAllowed(photos,message="只能上传图片类型")])
    submit = SubmitField('立即上传')
#修改密码
class UploadUser(FlaskForm):
    old_password = StringField('旧密码', validators=[DataRequired(), Length(6, 20, message="密码长度必须在6-20之间")])
    new_password = PasswordField('新密码', validators=[DataRequired(), Length(6, 20, message="密码长度必须在6-20之间")])
    confirm = PasswordField('确认密码',validators=[EqualTo('new_password',message="两次密码不一致")])
    submit = SubmitField('立即修改')
#修改邮箱
class UploadEmail(FlaskForm):
    old_email = StringField('Old_Email',validators=[Email(message="邮箱格式不正确")])
    new_email = StringField('New_Email',validators=[Email(message="邮箱格式不正确")])
    submit = SubmitField('立即修改')
#找回密码
class ZhaohuiMima(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), Length(6, 20, message="用户名必须在6到20位之间")])
    password = PasswordField('新密码', validators=[DataRequired(), Length(6, 20, message="密码长度必须在6到20位之间")])
    confirm = PasswordField('确认密码', validators=[EqualTo('password', message="两次密码不一致")])
    submit = SubmitField('立即修改')

app/views/users.py
import os
from flask import Blueprint,render_template,url_for,request,flash,get_flashed_messages,redirect,current_app
from app.forms import RegisterForm,LoginForm,UploadForm,UploadUser,UploadEmail,ZhaohuiMima
from werkzeug.security import generate_password_hash,check_password_hash
from app.models import User
from app.exts import db,photos
from app.email import send_mail
from flask_login import login_required,login_user,logout_user,current_user
from PIL import Image
users = Blueprint('users',__name__)


@users.route('/register/',methods=['GET','POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        u = User(username=form.username.data,password=form.password.data,email=form.email.data)
        db.session.add(u)
        db.session.commit()

        #生成token  用u对象调用模型中的方法
        token = u.generate_active_token()
        send_mail(u.email,'账户激活','email/activate',username=u.username,token=token)
        flash("恭喜注册成功,请点击邮件中的链接完成激活")
        return redirect(url_for('users.login'))
    return render_template('user/register.html',form=form)


#这个方法用来验证token  给用户邮箱发送过去一个完整的url
@users.route('/active/<token>',methods=['GET','POST'])
def active(token):
    if User.check_active_token(token):
        flash("账户激活成功")
        return redirect(url_for('users.login'))
    else:
        flash("账户激活失败")
        return redirect(url_for('main.index'))

@users.route('/login/',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if not u:
            flash("该用户名不存在")
        elif not u.confirmed:
            flash("该账户没有激活,请激活后登录")
        elif u.verify_password(form.password.data):
            login_user(u,remember=form.remember.data)
            flash("登录成功")
            return redirect( request.args.get('next') or url_for("main.index"))
        else:
            flash("密码不正确")
        return render_template('user/login.html')
    return render_template('user/login.html',form=form)
# 密码找回
@users.route('/mimazhaohui/',methods=['GET','POST'])
def mimazhaohui():
    form = ZhaohuiMima()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        u.password_hash = generate_password_hash(form.password.data )
        db.session.commit()
        if u.verify_password(form.password.data):
            flash('修改成功')
            return redirect(url_for('main.index'))
    return render_template('user/mimazhaohui.html',form=form)
@users.route('/logout/',methods=['GET','POST'])
def logout():
    logout_user()
    flash("退出登录成功")
    return redirect(url_for('main.shouye'))

@users.route('/test/',methods=['GET','POST'])
@login_required
def test():
    return 'this is test'

@users.route('/change_icon/',methods=['GET','POST'])
@login_required
def change_icon():
    img_url = ''
    form = UploadForm()
    if form.validate_on_submit():
        #获取文件后缀
        suffix = os.path.splitext(form.icon.data.filename)[1]
        #随机文件名  拼接
        filename = random_string()+suffix
        photos.save(form.icon.data,name=filename)
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],filename)
        img = Image.open(pathname)
        img.thumbnail((128,128))
        img.save(pathname)
        if current_user.icon != 'default.jpg':
            os.remove(current_app.config['UPLOADED_PHOTOS_DEST'],current_user.icon)
        current_user.icon = filename #将新上传的文件名 赋值给 用户的头像
        db.session.add(current_user)#保存在数据库中
        flash("头像上传成功")
        return redirect(url_for("users.change_icon"))
    img_url = photos.url(current_user.icon)
    return render_template('user/change_icon.html',form=form,img_url=img_url)

def random_string(length=20):
    import random
    base_str = 'abc123defhijklmnopqrstuvwxyz4567890'
    return ''.join(random.choice(base_str) for i in range(length))
#修改密码
@users.route('/xiugai/',methods=['GET','POST'])
@login_required
def xiugai():
    form=UploadUser()
    if form.validate_on_submit():
        u = User.query.filter_by(username=current_user.username).first()
        if u.verify_password(form.old_password.data):
            u.password_hash = generate_password_hash(form.new_password.data ) # 将查询出来的所有的title =='aaa1'的记录，全部修改为'aaa111'
            db.session.commit()
            if u.verify_password(form.new_password.data):
                flash('修改成功')
                return redirect(url_for('main.index'))
    return render_template('user/xiugai.html',form=form)
#修改邮箱
@users.route('/upload_email/',methods=['GET','POST'])
@login_required
def upload_email():
    form=UploadEmail()
    if form.validate_on_submit():
        u = User.query.filter_by(username=current_user.username).first()
        if u.email==form.old_email.data:
            u.email = form.new_email.data
            db.session.commit()
            flash("邮箱修改成功")
            return redirect(url_for('main.index'))
    return render_template('user/upload_email.html',form=form)
#个人中心
@users.route('/geren/',methods=['GET','POST'])
@login_required
def geren():
    img_url = current_user.icon
    return render_template('user/gerenzhongxing.html')

app/templates/user/change_icon.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/register.css">
</head>
<body>
<div class="content">
        {% extends 'bootstrap/base.html' %}
        {% import 'bootstrap/wtf.html' as wtf %}
        {#定制导航条#}
        {% block navbar %}
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url_for('main.shouye') }}">首页</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{{ url_for('main.index') }}">博客 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">新闻</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if current_user.is_authenticated %}
                                <li><a href="{{ url_for('users.logout') }}">退出</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">你好,{{ current_user.username }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('users.geren') }}">个人中心</a></li>
                                    <li><a href="{{ url_for('users.xiugai') }}">修改密码</a></li>
                                    <li><a href="{{ url_for('users.upload_email') }}">修改邮箱</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url_for("users.change_icon") }}">修改头像</a></li>
                                </ul>
                            </li>
                                {% else %}
                                <li><a href="{{ url_for("users.login") }}">登录</a></li>
                                <li><a href="{{ url_for("users.register") }}">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->

            </nav>
            <div class="background">
                <div class="contain">
                        {% for message in get_flashed_messages() %}
                            <div class="alert alert-warning alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                <strong>提示</strong> {{ message }}
                            </div>
                        {% endfor %}
                        {% block page_content %}
                            <img src="{{ img_url }}" alt="头像">
                            {{ wtf.quick_form(form) }}
                        {% endblock %}
                </div>
            </div>
        {% endblock %}
    </div>

</body>
</html>

app/templates/user/gerenzhongxing.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/register.css">
</head>
<body>
<div class="content">
        {% extends 'bootstrap/base.html' %}
        {% import 'bootstrap/wtf.html' as wtf %}
        {#定制导航条#}
        {% block navbar %}
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url_for('main.shouye') }}">首页</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{{ url_for('main.index') }}">博客 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">新闻</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if current_user.is_authenticated %}
                                <li><a href="{{ url_for('users.logout') }}">退出</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">你好,{{ current_user.username }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('users.geren') }}">个人中心</a></li>
                                    <li><a href="{{ url_for('users.xiugai') }}">修改密码</a></li>
                                    <li><a href="{{ url_for('users.upload_email') }}">修改邮箱</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url_for("users.change_icon") }}">修改头像</a></li>
                                </ul>
                            </li>
                                {% else %}
                                <li><a href="{{ url_for("users.login") }}">登录</a></li>
                                <li><a href="{{ url_for("users.register") }}">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->

            </nav>
            <div class="background">
                <div class="contain">
                        {% for message in get_flashed_messages() %}
                            <div class="alert alert-warning alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                <strong>提示</strong> {{ message }}
                            </div>
                        {% endfor %}
                        {% block page_content %}
                            <img src="{{ img_url }}" alt="头像">
                            <div class="photo">
                            </div>
                            <span>名称：{{ current_user.username }}</span>
                            <span>性别：{{ current_user.username }}</span>
                            <span>年龄：{{ current_user.username }}</span>
                            <span>个性签名：{{ current_user.username }}</span>
                        {% endblock %}
                </div>
            </div>
        {% endblock %}
    </div>

</body>
</html>

app/templates/user/login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/login.css">
</head>
<body>
    <div class="content">
        {% extends 'bootstrap/base.html' %}
        {% import 'bootstrap/wtf.html' as wtf %}
        {#定制导航条#}
        {% block navbar %}
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url_for('main.shouye') }}">首页</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{{ url_for('main.index') }}">博客 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">新闻</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if current_user.is_authenticated %}
                                <li><a href="{{ url_for('users.logout') }}">退出</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">你好,{{ current_user.username }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('users.geren') }}">个人中心</a></li>
                                    <li><a href="{{ url_for('users.xiugai') }}">修改密码</a></li>
                                    <li><a href="{{ url_for('users.upload_email') }}">修改邮箱</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url_for("users.change_icon") }}">修改头像</a></li>
                                </ul>
                            </li>
                                {% else %}
                                <li><a href="{{ url_for("users.login") }}">登录</a></li>
                                <li><a href="{{ url_for("users.register") }}">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->

            </nav>
            <div class="background">
                <div class="contain">
                    {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
        {{ wtf.quick_form(form) }}
        <span class="a">
            <a href="{{ url_for("users.mimazhaohui") }}">密码找回</a>
        </span>
        {% endblock %}
    </div>
</body>
</html>

app/templates/user/mimazhaohui.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/mimazhaohui.css">
</head>
<body>
    <div class="content">
        {% extends 'bootstrap/base.html' %}
        {% import 'bootstrap/wtf.html' as wtf %}
        {#定制导航条#}
        {% block navbar %}
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url_for('main.shouye') }}">首页</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{{ url_for('main.index') }}">博客 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">新闻</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if current_user.is_authenticated %}
                                <li><a href="{{ url_for('users.logout') }}">退出</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">你好,{{ current_user.username }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('users.geren') }}">个人中心</a></li>
                                    <li><a href="{{ url_for('users.xiugai') }}">修改密码</a></li>
                                    <li><a href="{{ url_for('users.upload_email') }}">修改邮箱</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url_for("users.change_icon") }}">修改头像</a></li>
                                </ul>
                            </li>
                                {% else %}
                                <li><a href="{{ url_for("users.login") }}">登录</a></li>
                                <li><a href="{{ url_for("users.register") }}">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->

            </nav>
            <div class="background">
                <div class="contain">
                    {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
        {% endblock %}
    </div>
</body>
</html>

app/templates/user/register.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/register.css">
</head>
<body>
<div class="content">
        {% extends 'bootstrap/base.html' %}
        {% import 'bootstrap/wtf.html' as wtf %}
        {#定制导航条#}
        {% block navbar %}
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url_for('main.shouye') }}">首页</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{{ url_for('main.index') }}">博客 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">新闻</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if current_user.is_authenticated %}
                                <li><a href="{{ url_for('users.logout') }}">退出</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">你好,{{ current_user.username }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('users.geren') }}">个人中心</a></li>
                                    <li><a href="{{ url_for('users.xiugai') }}">修改密码</a></li>
                                    <li><a href="{{ url_for('users.upload_email') }}">修改邮箱</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url_for("users.change_icon") }}">修改头像</a></li>
                                </ul>
                            </li>
                                {% else %}
                                <li><a href="{{ url_for("users.login") }}">登录</a></li>
                                <li><a href="{{ url_for("users.register") }}">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->

            </nav>
            <div class="background">
                <div class="contain">
                        {% for message in get_flashed_messages() %}
                            <div class="alert alert-warning alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                <strong>提示</strong> {{ message }}
                            </div>
                        {% endfor %}
                        {{ wtf.quick_form(form) }}
                </div>
            </div>
        {% endblock %}
    </div>

</body>
</html>